services:
  web:
    build: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
    networks:
      - custom_network
    depends_on:
      - redis
      

  redis:
    image: redis/redis-stack:latest
    container_name: redis 
    networks:
      - custom_network
    ports:
      - "6379:6379"
      - "8001:8001"

networks:
  custom_network:
    name: custom_network
    driver: bridge
